### ISSUE TITLE
Add categorical variable in the class space.

### ISSUE THREAD

**Issue by javiergonzalezh** [amzn/emukit#1]

**Comment by marpulli** [comment]
In some places (GPBayesianOptimization) we are using the number of parameters as a proxy for the number of model inputs. This will cause problems if we move to having parameters where we use one hot encoding. To fix this we should have a method like `parameter_space.get_n_model_inputs()`

**Comment by javiergonzalezh** [comment]
yes, in GPyOpt we have something like that too.

**Comment by apaleyes** [comment]
I like how transformations are implemented in skopt package: https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/space/transformers.py . As long as we can hide that from the user of the library, "transform" and "invert_transform" look like a very general concept we could use.

To make things easier, we can even apply a default identical transformation to variables that don't need anything like that, to keep things uniform. However maybe this is not need, not 100% sure at the moment.

@mapulli this may not be an issue. Both model and space are inputs for Emukit. So we operate under assumption that whatever space user defined is the what the model can consume already. So we can do transformations internally for optimization and under purposes, but as long as we do invert transformations before feeding the points to model/objective, we should be fine, right?
