### ISSUE TITLE
Number of iterations need to be set to zero in the loop state after completing the loop

### ISSUE THREAD

**Issue by javiergonzalezh** [amzn/emukit#111]
If we don't do this it is not possible to run the loop for more iterations when it is done.

**Comment by marpulli** [comment]
If we set the number of iterations in the loop state to zero we loose track of the total number of iterations done. When creating the stopping condition we could add on the number of iterations already completed. The current code is:

`stopping_condition = FixedIterationsStoppingCondition(stopping_condition)`

we could change to:

`stopping_condition = FixedIterationsStoppingCondition(stopping_condition + self.loop_state.iteration)`

**Comment by apaleyes** [comment]
Agreed with Mark's suggestion here. That would also allow us to track total number of iterations across all runs of the loop
