### ISSUE TITLE
Mac builds take a long time to complete

### ISSUE THREAD

**Issue by apaleyes** [amzn/emukit#125]
... and sometimes even timeout for transient reasons, succeeding on retry.

Let's try to investigate and see if we can cut this time down. Mark already started in #122

**Comment by marpulli** [comment]
Updating all brew packages seems to take about half of the build time. The python 3.5 build works without updating but 3.6 does not. The build is here:

https://travis-ci.org/amzn/emukit/builds/461907330?utm_source=github_status&utm_medium=notification

**Comment by marpulli** [comment]
The build time has halved with #128, are we happy or do we still want quicker?

**Comment by apaleyes** [comment]
Yes, let's close. osx builds now run just a bit longer than linux, all under 10 minutes, that should be good
