### ISSUE TITLE
Implement context variables

### ISSUE THREAD

**Issue by marpulli** [amzn/emukit#15]
This will allow us to fix certain parameters during the optimization

**Comment by apaleyes** [comment]
A bit more context, sorry for the word play.

Context should probably be a  property of the parameter space, so that you could write code like that:

```
space.fix_context(var1=1)
run_stuff()
space.reset_context()
```

**Comment by javiergonzalezh** [comment]
Question: are we considering that we can set a variable to a value even if is not defined as a context in the initial domain?

**Comment by marpulli** [comment]
@javiergonzalezh what's the use case for that?

**Comment by marpulli** [comment]
Here is what I propose for using the context in the optimization:

Change the signature of the candidate point calculator method to: `CandidatePointCalculator.compute_next_points(self, loop_state: LoopState, context: dict=None) -> np.ndarray`

The `OuterLoop` calls `ParameterSpace.get_context_manager()` to get a dictionary that descrives the context variables then passes it in to the point calculators. This dictionary will be converted to a GPyOpt context manager inside `AcquisitionOptimizer.optimize()` and we keep using the GPyOpt optimizers.

@apaleyes  What do you think?

**Comment by marpulli** [comment]
Done with #45
