### ISSUE TITLE
MultiSourceFunctionWrapper result: Wrong x-y-pairs for unsorted sources

### ISSUE THREAD

**Issue by dekuenstle** [amzn/emukit#154]
Hey,
if the input to a MultiSourceFunctionWrapper is not sorted by the source column, 
then the list of results has input in the original order, but output ordered by source.
I did not find any docs or checks about the input order.

```python
X = np.array([[x0, 0], [x1, 1], [x2, 0], [x3, 1]])
f = MultiSourceFunctionWrapper([f0, f1])
results = f.evaluate(X)

# input in results are in the expected order
results[0].X == [x0, 0]
results[1].X == [x1, 1]
...
# output is sorted by source
results[0].Y == f0([x0, 0])
results[1].Y == f0[x2, 0])
results[2].Y == f1([x1, 1])
results[3].Y == f1[x3, 1])
```
In my oppinion, the outputs should be resorted to the input order before [zipping them](https://github.com/amzn/emukit/blob/master/emukit/core/loop/user_function.py#L117). 
I can prepare a PR, if it is welcome.

Cheers, 
David

**Comment by marpulli** [comment]
Good catch, I agree that they should be resorted to the input order. 

A PR would be very welcome, thanks!
