### ISSUE TITLE
Replace pybnn with something stable

### ISSUE THREAD

**Issue by apaleyes** [amzn/emukit#164]
We install pybnn directly from sources. That makes us vulnerable to breaking changes in it ([example](https://travis-ci.org/amzn/emukit/builds/486634843)). Let's replace it with some other implementation that we can install from pip

**Comment by aaronkl** [comment]
Sorry about that. I'll will keep the master branch stable from now on

**Comment by apaleyes** [comment]
@aaronkl no worries. But is there any chance you could put it in pip? Then Emukit could just download a certain fixed version for integ tests, and never think about it again. The fact that we use pybnn shoun't be restricting you in the way you develop the package

**Comment by dekuenstle** [comment]
The pybnn version could also be fixed to a specific commit in the requirements file.
E.g. `-e git+https://github.com/automl/pybnn.git@1737a63d5b73852f68d575221032b32bdb180afe#egg=pybnn`

**Comment by apaleyes** [comment]
@dekuenstle yes, that would work, but it is also... intense, if I may? it just feels a bit weird to fix a version like this.

I think a tag though would make me feel much more comfortable. @aaronkl perhaps you could create a tag for pybnn?

**Comment by aaronkl** [comment]
I uploaded it on pip. You should be able now to install it through `pip install pybnn`

**Comment by apaleyes** [comment]
We do have a stable version 0.0.5, which we are going to use from now on for our integ tests. Thanks Aaron!
