### ISSUE TITLE
Unify return structure of test function

### ISSUE THREAD

**Issue by mmahsereci** [amzn/emukit#172]
Our test functions at the moment have various return structures. Some return the wrapped function, some the unwrapped function, and some return the parameter space in addition. Should we unify this?

**Comment by mmahsereci** [comment]
I will start doing this sometime soon. Any preferences? Of not I will go for 

return func_wrapped, space, func

for quadrature:

return func_wrapped, integral_bounds, func

**Comment by apaleyes** [comment]
Personally, I don't see much value in returning both func_wrapped and func, as func is available as a property of func_wrapped. But if others agree this is a useful convenience, i won't disagree for long.

**Comment by mmahsereci** [comment]
This is kind of done. Any more comments here?

**Comment by apaleyes** [comment]
Went through our test functions, and they all seem coherent in what they return: either function and space or function and integ bounds. Odd one out is sensitivity, but that's a different story. Thus agreed, let's close this!
