### ISSUE TITLE
cost sensitive loop

### ISSUE THREAD

**Issue by aaronkl** [amzn/emukit#18]
So far Emukit only considers the case where one has only one single model for the objective function. However, there are many cases, for example EIperSec, Fabolas, MTBO, .... , where one has two models: one for the objective function and one for the cost of evaluating the objective function.
It would be fairly straightforward to bootstrap from the already existing BayesianOptimizationLoop module to implement these methods. However, a cost sensitive loops seems to be a fundamental problem that might be also interesting for Bayesian quadrature or Experimental Design and I am wondering whether it makes sense to implement a general CostSensitiveOuterLoop class instead?

**Comment by marpulli** [comment]
Good idea, I agree that many different loops could use the cost model. 

We would either need the OuterLoop to accept two ModelUpdater classes, one for each model, or we would need to make a ModelUpdater class that deals with updating both models. We can make use of the acquisition function algebra to make a cost aware acquisition: `cost_aware_acquisition = acquisition_function/cost_acquisition` does this.

@apaleyes @javiergonzalezh Does this sound sensible to you?

**Comment by javiergonzalezh** [comment]
This makes total sense to me. I'd go for it.

**Comment by marpulli** [comment]
One other component we would need is a UserFunction that tells us how much a function evaluation cost, as well as the result of the function evaluation.

**Comment by apaleyes** [comment]
Yup, all that makes sense. Just one thing - we shouldn't create more outer loop classes for specific purposes. This is what the elements of the loop are for, and that is why they are so abstract and loosely coupled - to create new, then mix and match. So to introduce the concept of cost into Emukit we should create specific cost-aware model updaters, acquisition functions and/or user functions as needed.

**Comment by marpulli** [comment]
I just chatted to Andrei about this. We would like to have as few cost specific parts as possible. Here are some ideas:
- We would pass in a list of `ModelUpdater`s to the `OuterLoop`. For the cost model case it would call `update()` on both model updaters. It should be able to deal with either one or a list of them. We would need to be able to tell a `ModelUpdater` whether it should use `Y` or `cost` as the training targets.
- The `UserFunctionWithCost` would change depending on what exactly the cost is, so we might want to leave this to the user for now, but if there are common cases (such as timing the function evaluation), we could provide this functionality.
- We can probably just add a `cost` field to the `UserFunctionResult` with a default value of `None`.
- We need to add `cost` as a property of `LoopState`.

I agree about not needing any new interface for the acquisitions. 

What do you think?

**Comment by aaronkl** [comment]
Sounds good to me. It will reduce code duplication and allows us to update an arbitrary amount of models in the loop. Besides adding a cost field to the `UserFunctionResult`, maybe it would also make sense to add an additional dict `additional_info` which allow users to store any additional information?

**Comment by apaleyes** [comment]
Do you have examples of other types of information that may go in that field? Unless there is a compelling reason, I'd rather avoid `additional_info` just yet, as it tends to complicate things in long run

**Comment by aaronkl** [comment]
Well typical examples would be to store learning curves or training and validation error. However, these are special use cases for hyperparameter optimization so probably it would be better if we do not add this field yet

**Comment by marpulli** [comment]
Are you able to have a go at implementing this? We can have a look but we will be working on everything labelled '1.0' first, so it might take us a while to get around to it.

**Comment by aaronkl** [comment]
sure I can do that

**Comment by marpulli** [comment]
Closed with #39
