### ISSUE TITLE
Bug in notebooks/Emukit-Categorical-with-Tensorflow.ipynb

### ISSUE THREAD

**Issue by MalteEbner** [amzn/emukit#193]
In cell 8 of the notebook Emukit-Categorical-with-Tensorflow.ipynb following line is used:
`loop = BayesianOptimizationLoop(rf_model, space)`

This causes an error as the constructor of the class BayesianOptimizationLoop in file emukit/bayesian_optimization/loops/bayesian_optimization_loop.py is defined as 
`class BayesianOptimizationLoop(OuterLoop):
    def __init__(self, space: ParameterSpace, model: IModel, ...)`

Changing the notebook line to 
`loop = BayesianOptimizationLoop(space, rf_model)` solved the error for me.

**Comment by aaronkl** [comment]
I've already created a PR #193 for that

**Comment by apaleyes** [comment]
Appears to be fixed in #192
