### ISSUE TITLE
implementing random search baseline

### ISSUE THREAD

**Issue by aaronkl** [amzn/emukit#206]
It would be very convenient for developing and benchmarking to have a random search baseline that implements the OuterLoop interface such that, for example, it can easily be plugged into the benchmarking module
A trivial way to do that would be to implement a dummy ModelUpdate and a new CandidatePointSelector which simply returns a random data point. What do you think?

**Comment by marpulli** [comment]
I agree this would be very useful and the way you suggest is sensible. 

It might also be interesting to include some other, potentially stronger, baselines such as Sobol sequences or Latin Hypercubes. The implementation would be a bit more complex however.
