### ISSUE TITLE
Get rid of model_free designs

### ISSUE THREAD

**Issue by apaleyes** [amzn/emukit#219]
While working on #216, I had an idea of simplifying the experimental_design package.

At the moment we have model_free and model_based parts in there. model_based is what emukit is all about, and i think this part is just fine. model_free currently has Random, which is a thin wrapper around `space.sample_uniform`, and Latin, which is a thin wrapper around [pyDOE](https://pythonhosted.org/pyDOE/randomized.html#latin-hypercube). Both are used essentially as just input generator utilities, and aren't used anywhere inside the library. We cannot even argue them to be a core part of emukit itself, as, like said above, they are just thin wrappers around something else.

I am going to argue that there is nothing they actually contribute to emukit. We already have random elsewhere, and Latin is a small bit of a well-design library pyDOE which our users may use if they so wish. We can even point them to it in the docs. So I suggest we remove these, and leave experimental_design package like that:

experimental_design
|_ interfaces
|_ acquisitions
|_ experimental_design_loop.py

essentially removing the whole model free/model based dichotomy from the library.

**Comment by marpulli** [comment]
I'm not convinced that removing them is a good idea. They are certainly useful in our example notebooks for creating initial designs so I would expect them to be useful for customers too. 

Looking at the [code](https://github.com/amzn/emukit/blob/645eb88c07e4f3ec3fc6e7ff16e1428f4846720c/emukit/experimental_design/model_free/latin_design.py#L22) required to use pyDOE to create some samples, it is quite a few lines, and we do things like round the samples in case of discrete variables, which a customer could quite easily forget to do.

We could also consider renaming them so customers are more aware of their intended purpose - to create initial designs.

**Comment by apaleyes** [comment]
Sounds reasonable.

Perhaps then another approach would be to further extend our recent addition of `ParameterSpace.sample_uniform` API? Something like that:

```
class ParameterSpace:
    def sample(self, n: int, design: InitialDesign.Random) -> np.ndarray:
    # other options include Latin, Sobol, maybe few more from pyDOE
```

thus moving the whole thing into `emukit.core.initial_designs`

**Comment by mmahsereci** [comment]
my two cents: I agree with @marpulli that they are quite useful. I see them a bit like initial designs/sampling schemes in auto-diff frameworks (they usually have quite afew). It is not really what auto-diff is about but without them it would be much more of a hassle to use the library. 

Moving into core.initial_designs sounds reasonable, as the term (and the designs) are quite agnostic to the method they are being used with.

**Comment by apaleyes** [comment]
done

**Comment by tdiethe** [comment]
Note that the [Bayesian Optimization tutorial](https://amzn.github.io/emukit/bayesian-optimization/) still refers to model_free, i.e. the line:

`from emukit.experimental_design.model_free.random_design import RandomDesign`

which leads to the following error when copy/pasting the sample code:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-28-32962e6ab93a> in <module>
----> 1 from emukit.experimental_design.model_free.random_design import RandomDesign
      2 from GPy.models import GPRegression
      3 from emukit.model_wrappers import GPyModelWrapper
      4 
      5 design = RandomDesign(parameter_space) # Collect random points

ModuleNotFoundError: No module named 'emukit.experimental_design.model_free'
```
