### ISSUE TITLE
More control over MCMC for kernel parameter integration

### ISSUE THREAD

**Issue by henrymoss** [amzn/emukit#236]
The IntegratedHyperParameterAcquisition function only provides control over the number of samples. To control other MCMC parameters (like leapfrog step size and burn in) you need to hardcode in the model wrapper.

I propose adding these extra values as inputs to the IntegratedHyperParameterAcquisition

**Comment by apaleyes** [comment]
Sounds reasonable. Would you be willing to create a PR with these changes?
