### ISSUE TITLE
What is a reason to use scipy==1.1.0?

### ISSUE THREAD

**Issue by aeivazi** [amzn/emukit#295]
Scipy latest version is `1.4.1` any specific reason to depend on such an old version of `scipy`?

**Comment by apaleyes** [comment]
No, there is no specific reason. We can fix it, or if you wish to use this opportunity to submit a PR - feel free!

**Comment by aeivazi** [comment]
Thanks @apaleyes for a quick response I will be happy to PR.
One more question: would you mind to relax requirements for `emcee` to low bound as well?
