### ISSUE TITLE
Tracking points in outer loop

### ISSUE THREAD

**Issue by charelstoncrabb** [amzn/emukit#308]
Currently the next candidate points are tracked only via logging output--tracking this as a data member would be much more useful.

I would be happy to submit a (2-line) PR, how might I push a branch?

**Comment by apaleyes** [comment]
you would need to fork emukit and submit a PR from there. Refer to, for example, this guide: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by apaleyes** [comment]
@mmahsereci made a good observation in the PR, noting that this data is already stored in the loop state. I haven't read the actual feature description closely enough the first time to realize that. Is that indeed sufficient for your needs @charelstoncrabb ?

**Comment by mmahsereci** [comment]
I am closing this issue for now as the feature requested seems to be implemented already. @charelstoncrabb , feel free to open an issue again in case you have further questions. Thanks!
