### ISSUE TITLE
Tests fail with scipy >= 1.5

### ISSUE THREAD

**Issue by apaleyes** [amzn/emukit#316]
At the moment tests pass with `scipy==1.4.1` and fail with `scipy==1.5.1`. That's weird.

Originally discussed in #315

**Comment by ekalosak** [comment]
For convenience, here's the comparison for 1.5.1 v 1.4.1 in scipy: https://github.com/scipy/scipy/compare/v1.5.1...v1.4.1

**Comment by mmahsereci** [comment]
closing, as this seems to be fixed with PR #318 .
