### ISSUE TITLE
find a place for mcmc_sampler.py

### ISSUE THREAD

**Issue by mmahsereci** [amzn/emukit#58]
it is currently in bayesian_optimization/util/ and 'util' is not a good place to be.

**Comment by apaleyes** [comment]
I suggest to put `mcmc_sampler.py` in _emukit/samplers_ even though it is the only one we have so far, and `epmgp.py` in _emukit/bayes_opt_ (for a lack of better place and because I have hard time classifying this file at all).

**Comment by javiergonzalezh** [comment]
fine with me!
