### ISSUE TITLE
Use abstractions appropriately

### ISSUE THREAD

**Issue by apaleyes** [amzn/emukit#63]
Before going 1.0 we should review our use of abstractions. Based on recent conversations I propose this approach:

* On OuterLoop level we should be dealing in ModelUpdater, CandPointCalc and so on.
* On concrete method level we should be dealing in problem specific terms: acquisition, update step size, etc.
* If concrete method does not suit user needs, it should be clear how to create own implementation of the OuterLoop. In fact, users should be encouraged to do that.

There are few places in the code base where we currently don't follow this approach, and if everyone agrees with this proposal, we should identify and fix those places.

**Comment by apaleyes** [comment]
@marpulli @javiergonzalezh @mmahsereci let me know your thoughts!

**Comment by javiergonzalezh** [comment]
I agree with this. One of the things that we need to do is to separate the logic of computing the next points from the logic of optimizing an acquisition that is passed in. In the sequential way of collecting points it make sense having them together but as soon as we start computing batches things can be more complex.

**Comment by javiergonzalezh** [comment]
Closing as Mark sorted this one out already.

**Comment by apaleyes** [comment]
Let's keep it open for now, as we still need to review the loop's APIs to make sure they are consistent.
