### ISSUE TITLE
Organize folder 'examples'

### ISSUE THREAD

**Issue by javiergonzalezh** [amzn/emukit#72]
The examples folders in going to contain methods that have been built with emukit but that are not necessarily a core part of the library. To keep that folder organized as it grows we need to set up some standards. Let's at least create a new folder for each new example with a descriptive name. Something like this:

https://github.com/apache/incubator-mxnet/tree/master/example

**Comment by apaleyes** [comment]
We may also need some kind of indexing, which could go into separate file, or into readme inside that folder

**Comment by javiergonzalezh** [comment]
Sure! Before starting moving things around let me know if you agree with this:

**Notebooks folder:**
We can rename it as tutorials (which is more informative) and it should contain notebooks that illustrate different features of the library. These may be long tutorials of a short illustration of a new feature. These are stand alone notebooks that don't require any extra file and fully sit on Emukit components. The goal of the tutorials is *to learn how to use Emukit.*

**Examples folder:**
Each example lives in a separated folder and may call some extra files. I see examples of two types:

- Elaborated notebooks (what we call tasks) that tell a narrative about a *problem/question* that can be studied with the elements of Emukit. An example of this is the analysis of the properties of a simulator using emukit components.

- The implementation of new *methods*, that use emukit components. These can live in a .py file, should have tests and ideally should be delivered together with a small illustrative notebook. These can be, for instance, the implementation of a method of a research paper. I some cases we may consider incorporated these to the core of the library if they can be reused.
 
Does it make sense?

**Comment by apaleyes** [comment]
That sounds like an excellent plan, thanks Javier. The only technical difficulty here would be testing examples. Right now we put all those tests in integration tests folder, and that is probably fine. But we could also consider keeping tests of a specific example next to the example itself. Which would look more logical, but would be just a bit trickier to automate in Travis build.
